# Generated by Django 4.2.7 on 2023-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='first_work_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
