# Generated by Django 4.2.7 on 2023-12-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console1', '0003_worker_birth_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
