# Generated by Django 4.2.7 on 2023-12-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console1', '0004_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chef',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Worker.chef+', to='console1.worker'),
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, db_column='Comments', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Worker.courier+', to='console1.worker'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
