# Generated by Django 4.2.7 on 2023-12-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console1', '0006_remove_order_courier_customer_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Worker.courier+', to='console1.worker'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='console1.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Worker.chef+', to='console1.worker'),
        ),
    ]
