# Generated by Django 4.2.7 on 2023-12-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console1', '0008_deliveryinfo_delivery_info_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza_1_amount',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_2_amount',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_3_amount',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_4_amount',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza_5_amount',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
