# Generated by Django 4.2.7 on 2023-12-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console1', '0009_alter_order_pizza_1_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_info_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='console1.deliveryinfo'),
        ),
    ]
