# Generated by Django 4.2.7 on 2023-12-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console1', '0010_remove_deliveryinfo_order_order_delivery_info_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_info_id',
            new_name='delivery_info',
        ),
    ]
