# Generated by Django 4.2.7 on 2023-12-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console1', '0011_rename_customer_id_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='critical_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
