# Generated by Django 4.2.7 on 2023-12-20 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console1', '0012_product_critical_amount_alter_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='product_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_10_set', to='console1.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_10_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_11_set', to='console1.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_11_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_12_set', to='console1.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_12_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_13_set', to='console1.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_13_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_14_set', to='console1.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_14_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_15_set', to='console1.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_15_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_1_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_2_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_3_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_4_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_5_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_6_set', to='console1.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_6_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_7_set', to='console1.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_7_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_8_set', to='console1.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_8_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_9_set', to='console1.product'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product_9_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pizza',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='console1.pizza'),
        ),
    ]
