# Generated by Django 4.2.7 on 2023-12-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console1', '0013_recipe_product_10_recipe_product_10_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Принят', 'Принят'), ('Ожидает', 'Ожидает'), ('Готовится', 'Готовится'), ('Отменён', 'Отменён'), ('Готов', 'Готов'), ('Завершён', 'Завершён')], max_length=15, null=True),
        ),
    ]
