# Generated by Django 4.2.7 on 2023-12-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console1', '0016_employee_alter_deliveryinfo_courier_alter_order_chef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Принят', 'Принят'), ('Ожидает', 'Ожидает'), ('Готовится', 'Готовится'), ('Отменён', 'Отменён'), ('Готов', 'Готов'), ('Доставляется', 'Доставляется'), ('Завершён', 'Завершён')], max_length=15, null=True),
        ),
    ]
